services:
  skillpath:
    image: zerogamer/skillpath-web:latest
    container_name: skillpath_app
    ports:
      - "3000:3000"
    logging:
      driver: loki
      options:
        loki-url: "http://host.docker.internal:3100/loki/api/v1/push"
        loki-external-labels: job=skillpath,env=dev
